import DataObject from './utils/dataObject';

export type configRaw = {
  game_id: string,
  server_id: string,
  applicationTitle: string,
  current_version_mobile: number,
  urlRequestServer: string,
  url_domain: string,
  urlPublic: string,
  urlPlatformRequest: string,
  url_changelog: string,
  url_facebook: string,
  registrationSource: string,
  url_forum_teams: string,
  url_forum: string,
  url_support: string,
  url_app_rating: string,
  url_tos: string,
  url_policy: string,
  urlSwfMain: string,
  urlSwfCharacter: string,
  urlSwfUi: string,
  urlSwfMovieCover: string,
  urlStorePlayata: string,
  localeVersion: string,
  constantsVersion: string,
  dungeons_enabled: boolean,
  titles_enabled: boolean,
  itemsets_enabled: boolean,
  custom_guild_backgrounds_enabled: boolean,
  fan_foto_enabled: boolean,
  battle_skills_enabled: boolean,
  multitasking_booster_enabled: boolean,
  movie_tournaments_enabled: boolean,
  hide_panties_allowed: boolean,
  dating_enabled: boolean,
  isFriendbarSupported: boolean,
  emoticons_enabled: boolean,
  blockRegistration: boolean,
  registration_enabled: boolean,
  video_advertisment_enabled: boolean,
  video_advertisment_cooldown_tooltip_enabled: boolean,
  secure_requests_enabled: boolean,
  team_locale_enabled: boolean,
  special_offer_shop_enabled: boolean,
  offerwall_enabled: boolean,
  locales: string[],
  locale_map: any,
  locale_names: any,
  locale_country_names: any,
  alternative_locales: string[],
  payment_alternative_locales: string[],
};

export class ExtendedConfig extends DataObject<configRaw> {

}

export default new ExtendedConfig();
